name: CI/CD with VSCE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Publish VSIX
        env:
          VSCE_PAT: ${{ secrets.AZURE_TOKEN }} # Personal Access Token for VSCE
        run: npx vsce package --out Smart_Code.vsix -p $VSCE_PAT
