name: CI/CD with VSCE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Dependencies
        run: npm install

      - name: Authenticate with VSCE
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.AZURE_TOKEN }}" > ~/.npmrc

      - name: Package VSIX
        run: npx vsce package --out dist/Smart_Code.vsix

      - name: Generate Changelog
        run: npx auto-changelog --output CHANGELOG.md

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Add changes"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
